# Generated by Django 3.1.4 on 2022-05-21 18:09

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('imageurl', models.CharField(blank=True, max_length=1000, null=True)),
                ('yes_no', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(choices=[(0, 'Is'), (1, 'Does')], default=0)),
                ('quest', models.CharField(max_length=1000)),
            ],
        ),
    ]
